version: '3.0'

services:

  # Mail server running on separate image
  mail:
    image: tvial/docker-mailserver:latest
    restart: always
    domainname: example.com
    volumes:
      - maildata:/var/mail
      - mailstate:/var/mail-state
      - ./.docker/dev/mail/config/:/tmp/docker-mailserver/
    environment:
      - ENABLE_SPAMASSASSIN=0
      - ENABLE_CLAMAV=0
      - ENABLE_FAIL2BAN=0
      - ENABLE_POSTGREY=0
      - ENABLE_MANAGESIEVE=1
      - ONE_DIR=1
      - DMS_DEBUG=0
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    networks:
      - default

  snappymail:
    image: leojonathanoh/snappymail:merge
    ports:
      - 8888:8888
    volumes:
      - snappymail:/snappymail/data
    networks:
      - default
      - db-network

  # MySQL database
  db:
    image: mysql:5.7
    hostname: db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=snappymail
      - MYSQL_PASSWORD=snappymail
      - MYSQL_DATABASE=snappymail
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - db-network

networks:
  default:
  db-network:
    internal: true

volumes:
  maildata:
    driver: local
  mailstate:
    driver: local
  snappymail:
    driver: local
  mysql:
    driver: local
