version: '2'
services:
  snappymail:
    image: leojonathanoh/snappymail:merge
    ports:
      - 8888:8888
    volumes:
      - snappymail:/snappymail/data
    networks:
      - default

networks:
  default:

volumes:
  snappymail:
    driver: local
