version: '2'
services:
  snappymail:
    image: leojonathanoh/snappymail:merge
    ports:
      - 8888:8888
    volumes:
      - snappymail:/var/lib/snappymail
    networks:
      - default
      - db-network
      - redis-network
    restart: unless-stopped

  mysql:
    image: mariadb:10
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=snappymail
      - MYSQL_PASSWORD=snappymail
      - MYSQL_DATABASE=snappymail
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - db-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    networks:
      - redis-network
    restart: unless-stopped

networks:
  default:
  db-network:
    internal: true
  redis-network:
    internal: true

volumes:
  mysql:
    driver: local
  snappymail:
    driver: local
